#1. Narzędzia pracy z sztuczną inteligencją

Przed rozpoczęciem pracy z zagadnieniem sztucznej inteligencji, przyszedł czas na ważną decyzję jaką jest wybranie odpowiedniej biblioteki. Język Python posiada wiele dużych [**bibliotek**](https://codersera.com/blog/python-libraries-for-data-science/) zoptymalizowanych w tym zakresie.

Powyższy artykuł przedstawia listę najlepszych bibliotek z roku 2021. Warto wiedzieć, że każda z tych bibliotek ma swoje wady i zalety. Bez wchodzenia w konkretne [**zalety**](https://www.geeksforgeeks.org/why-tensorflow-is-so-popular-tensorflow-features/), głownym narzędziem pracy będzie TensorFlow.

#2. Tensorflow

Jest jedną z najbardziej popularnych bibliotek na rynku. Używana jest chociażby przez takie firmy jak Google, Qualcomm, Dropbox, czy nawet Tinder. Dla osób zainteresowanych samą biblioteką odsyłam do [**tego artykułu**](https://greenlogic.pl/blog/tensorflow-darmowa-biblioteka-machine-learning-dla-kazdego/). W celu możliwości dalszej pracy, musimy jednak poznać podstawowe mechanizmy działania biblioteki.

W celu zainstalowania na urządzeniu lokalnym biblioteki, potrzebne jest użycie narzędzia pip.
~~~
pip install tensorflow
~~~

Nie będzie to konieczne w tym kursie, ponieważ Google Colaboratory posiada domyślnie wgraną bibliotekę, którą wczytujemy za pomocą komendy.





In [ ]:
%tensorflow_version 2.x  # jest to wymagane tylko w Google Colab, sprecyzowanie której wersji będziemy używać
import tensorflow as tf  # import biblioteki

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # jest to wymagane tylko w Google Colab, sprecyzowanie której wersji będziemy używać`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


##Tensory
"Status tensora jest specyficzny: z jednej strony jest uogólnieniem wektora, a z drugiej jego szczególnym przypadkiem" (https://smp.uph.edu.pl/msn/45/19-24.pdf). Tensory są podstawowym elementem biblioteki Tensorflow, należy je traktować jako zmienne w programowaniu, na których będą wykonywane operacje. Żeby to było możliwe każdy z nich posiada właściwości takie jak rodzaj i kształt.

Rodzaj tensora odpowiada popularnym typom zmiennych spotykanych w każdym języku programwania jak: integer, float, string, lub inne. Pełna lista znajduję się w [dokumentacji](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType). 


In [ ]:
v_number = tf.Variable(20, tf.int16)
v_float = tf.Variable(3.14, tf.float64)
v_string = tf.Variable("a string", tf.string) 

###Ranga
Jest ona właściwością opisującą rangę zmiennej, mówi ona jakie jest najgłębsze zagnieżdzenie w tensorze:
* [ 0 ] Skalar - pojedyncza zmienna bez osi


In [ ]:
ranga0 = tf.Variable("test123", tf.string)
tf.rank(ranga0)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

Ranga zmiennej jest pokazana poprzez właściwość *numpy*
* [ 1 ] Wektor - wiele zmiennych z jedną osią

In [ ]:
ranga1 = tf.Variable(["test1", "test2"], tf.string)
tf.rank(ranga1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

* [ 2 ] Macierz - wiele zmiennych na dwóch osiach

In [ ]:
ranga2 = tf.Variable([["test1", "test2"], ["test3", "test4"]], tf.string)
tf.rank(ranga2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Warto wiedzieć, że można tworzyć tensory o wiekszej ilości wymiarów.

###Kształt

Ostatnią własnością tensorów, którą musimy poznać i zrozumieć jest ich kształt. Jest to właściwość mówiąca ile elementów znajduje się na każdej z ich osi.

In [ ]:
ranga1.shape

TensorShape([2])

In [ ]:
ranga2.shape

TensorShape([2, 2])

Tensor ten zawiera 2 elementy, z czego każdy z nich posiada 2 wartości

In [ ]:
shapex = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int32)
shapex.shape

TensorShape([2, 3])

Tensor ten zawiera 2 elementy, z czego każdy z nich posiada 3 wartości. 

##Keras

Początkowo Keras istniał jako osobna biblioteka służąca do pracy z sztuczną inteligencją, posiada kilka kluczowych zalet które przyczyniły się do jego zintegrowania z świetną, ale ciężką w pracy z biblioteką Tensorflow. Z tego powodu Keras jest częścią biblioteki od wersji 2.0 w górę. Te zalety, którymi dysponował Keras to między innymi:

* Szybka i zomptymalizowana praca na niższym poziomie 
* Skalowalność obliczeń do wielu urządzeń
* Eksportowanie programów do zewnętrznych środowisk, takich jak serwery, przeglądarki czy urządzenia mobilne.

Zachęcam do eksperymentowania z rozmiarem tensorów w tym przykładzie. Istnieje również kilka wbudowanych metod, które pozwalają na modyfikowanie tensorów, zostaną one wprowadzone wraz z kolejnymi lekcjami. Po więcej informacji dla osób zainteresowanych odsyłam do dokumentacji pod adresem https://www.tensorflow.org/guide/tensor.
